//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFAreaScreenRecorder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint VideoEncoderNumber {
            get {
                return ((uint)(this["VideoEncoderNumber"]));
            }
            set {
                this["VideoEncoderNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint VideoEncoderMode {
            get {
                return ((uint)(this["VideoEncoderMode"]));
            }
            set {
                this["VideoEncoderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint VideoEncoderMediaType {
            get {
                return ((uint)(this["VideoEncoderMediaType"]));
            }
            set {
                this["VideoEncoderMediaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint FileFormatNumber {
            get {
                return ((uint)(this["FileFormatNumber"]));
            }
            set {
                this["FileFormatNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StoringDir {
            get {
                return ((string)(this["StoringDir"]));
            }
            set {
                this["StoringDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint VideoSourceStream {
            get {
                return ((uint)(this["VideoSourceStream"]));
            }
            set {
                this["VideoSourceStream"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public uint VideoSourceMediaType {
            get {
                return ((uint)(this["VideoSourceMediaType"]));
            }
            set {
                this["VideoSourceMediaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CursorMask {
            get {
                return ((int)(this["CursorMask"]));
            }
            set {
                this["CursorMask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCursor {
            get {
                return ((bool)(this["ShowCursor"]));
            }
            set {
                this["ShowCursor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 100, 255, 100")]
        public global::System.Drawing.Color MaskColor {
            get {
                return ((global::System.Drawing.Color)(this["MaskColor"]));
            }
            set {
                this["MaskColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double VideoCompressionQuality {
            get {
                return ((double)(this["VideoCompressionQuality"]));
            }
            set {
                this["VideoCompressionQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioSourceStream {
            get {
                return ((uint)(this["AudioSourceStream"]));
            }
            set {
                this["AudioSourceStream"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioSourceMediaType {
            get {
                return ((uint)(this["AudioSourceMediaType"]));
            }
            set {
                this["AudioSourceMediaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioEncoderNumber {
            get {
                return ((uint)(this["AudioEncoderNumber"]));
            }
            set {
                this["AudioEncoderNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioEncoderMode {
            get {
                return ((uint)(this["AudioEncoderMode"]));
            }
            set {
                this["AudioEncoderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint AudioEncoderMediaType {
            get {
                return ((uint)(this["AudioEncoderMediaType"]));
            }
            set {
                this["AudioEncoderMediaType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public double AudioCompressionQuality {
            get {
                return ((double)(this["AudioCompressionQuality"]));
            }
            set {
                this["AudioCompressionQuality"] = value;
            }
        }
    }
}
